<?php 

	require_once('includes/OAuth.php');

	$api = 'https://www.pesapal.com';
	 
	$token = $params 	= NULL;
	$iframelink 		= $api.'/api/PostPesapalDirectOrderV4';
	
	//Kenyan keys
	$consumer_key 		= "eWaD78uiT/1VLvvty8zzWhnUsajVfh5b";  
	$consumer_secret 	= "iw1NN5ibZsdqViVRv/zRhOLMk4s=";
	 
	$signature_method	= new OAuthSignatureMethod_HMAC_SHA1();
	$consumer 			= new OAuthConsumer($consumer_key, $consumer_secret);
	 
	



	$amount 		= str_replace(',','',$_POST['price']); // remove thousands seperator if included
	$amount 		= number_format($amount, 2); //format amount to 2 decimal places
	$desc 			= 'TaunWiFi Payment';
	$type 			= 'MERCHANT';	
	$phonenumber	= $_POST['phone'];
	$currency 		= 'UGX';
	$dns 			= $_POST["dns"]; 
	$n = 10;  
	function getRandomString($n) {
    return bin2hex(random_bytes($n / 2));
	}   
	$reference = "taunwifi".getRandomString($n);  //unique transaction id, generated by merchant.
	$callback_url = 'http://localhost/taunwifi/listener.php';
	//$callback_url 	= '[domain]/pesapalPHPExample/redirect.php'; //URL user to be redirected to after payment



	//Record order in your database.
	//$database = new pesapalDatabase();
	//$database->store($_POST); 
	$sql = "INSERT INTO transactions (amount, phone, Ref, date)
    VALUES ('$amount', '$phonenumber', '$reference', '$date')";
		
	$post_xml	= "<?xml version=\"1.0\" encoding=\"utf-8\"?>
				   <PesapalDirectOrderInfo 
						xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" 
					  	xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" 
					  	Currency=\"".$currency."\" 
					  	Amount=\"".$amount."\" 
					  	Description=\"".$desc."\" 
					  	Type=\"".$type."\" 
					  	Reference=\"".$reference."\" 
					  	FirstName=\"".$first_name."\" 
					  	LastName=\"".$last_name."\" 
					  	Email=\"".$email."\" 
					  	PhoneNumber=\"".$phonenumber."\" 
					  	xmlns=\"http://www.pesapal.com\" />";
	$post_xml = htmlentities($post_xml);
	
	//post transaction to pesapal
	if(mysqli_query($con, $sql)){
	$iframe_src = OAuthRequest::from_consumer_and_token($consumer, $token, "GET", $iframelink, $params);
	$iframe_src->set_parameter("oauth_callback", $callback_url);
	$iframe_src->set_parameter("pesapal_request_data", $post_xml);
	$iframe_src->sign_request($signature_method, $consumer, $token);
}else{
	echo "ERROR: Something went wrong";
}
?>  
